# Generated by Django 5.0 on 2023-12-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('customer_number', models.CharField(max_length=20, unique=True)),
                ('meter_serial_number', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
