# Generated by Django 5.0 on 2023-12-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.AlterField(
            model_name='customer',
            name='cus_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
